[project]
name = "amazon-order-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "rich>=13.9.4",
    "selenium>=4.29.0",
    "webdriver-manager>=4.0.2",
]
